substitutions:
  name: test

esphome:
  name: $name

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret password

ota:
  - platform: esphome
    password: !secret password

wifi:
  ssid: !secret wifi_ssid 
  password: !secret wifi_password
  domain: !secret wifi_domain

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret hotspot_ssid
    password: !secret hotspot_password

captive_portal:

binary_sensor:
  - platform: gpio
    name: "Pin GPIO23"
    pin: GPIO23

